[package]
name = "raft"
version = "0.1.0"
authors = ["Nicholas Dujay <nickdujay@gmail.com>"]

[lib]
name = "raft"
path = "src/lib.rs"

[[bin]]
name = "raftd"
path = "src/main.rs"

[dependencies]
rand = "0.3"
log = "^0.3"
env_logger = "^0.4"
error-chain = "^0.7"
clap = "^2"
